### ISSUE TITLE
error: unknown resource type 'command:local:Command'

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-command#200]
### What happened?

When running an internal Pulumi stack, the execution failed:

```
 command:local:Command ([redacted resource name]):
    error: unknown resource type 'command:local:Command'
```

### Expected Behavior

Expect that `new local.Command(...)` should not fail with an unknown resource type error.

### Steps to reproduce

Unknown, unable to reproduce independently from report.

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dougludlow** [comment]
I was just going to create an issue for this as well. This just started occurring for us in a couple projects a few days ago. One project is using v3.43.1 of pulumi, the other is using v3.64.0. I've tried upgrading pulumi and that didn't make a difference. I found a workaround to reinstall the plugin via `pulumi plugin install resource command v0.7.2 --exact --reinstall`. However, this has stopped working. I'm wondering if the plugin binary is somehow corrupt?

**Comment by AaronFriel** [comment]
@dougludlow are you using GitHub Actions as your CI environment? I wonder if you could use the UI or API to clear your caches and see if the issue reoccurs:

GitHub UI location is: `https://github.com/ORG/REPO/actions/caches`

**Comment by dougludlow** [comment]
No, we're using GitLab. We're using`pulumi/pulumi:3.43.1` as the image and the steps aren't too different from above.

**Comment by AaronFriel** [comment]
Could you try updating to pulumi v3.69.0 and see if the problem reproduces? 3.43.1 is fairly old (between 6 and 12 months). 

We created the issue after an internal report, but we haven't been able to reproduce. If updating Pulumi in your stack resolves the issue, perhaps we can consider this fixed by an interim release.

**Comment by dougludlow** [comment]
Upgrading didn't resolve. The only thing I've been able to do to resolve it is reinstall the binary. 

I noticed that when I run `pulumi plugin ls` that the corrupt resource plugin is 31 MB and then when I reinstall it with `pulumi plugin install resource command v0.7.2 --exact --reinstall` it is 32 MB. 

Do you think it's possible that there is a bad version of the plugin cached in the edge someplace and we happen to be getting it on occasion?

**Comment by AaronFriel** [comment]
@dougludlow Can you create archives of `~/.pulumi/plugins/resource-command-v0.7.2` and reproduce, and send that archive to me at friel at pulumi dot com?

**Comment by AaronFriel** [comment]
@dougludlow Update: we've root caused and have a path to resolution. Pulumi provider binaries are uploaded to two locations, GitHub Releases and get.pulumi.com, backed by a storage bucket & CDN.

When rate limits cause acquiring the release from GitHub to fail, the CLI falls back to acquiring from get.pulumi.com. We haven't determined why yet, but it appears an old release (possibly v0.0.0) has been published to S3 instead of v0.7.2. That causes the error seen in the title.

**Comment by AaronFriel** [comment]
This should be resolved, we've ensured the release artifacts are in sync and have found the root cause, an incorrect publishing configuration on another provider.

**Comment by dougludlow** [comment]
Thanks for figuring this out. It was driving us nuts!
